logging:
  config: classpath:log4j2.xml
spring:
  application:
    name: hjc-login
  profiles:
    active: ${server_env:remote}
  datasource:
    druid:
      initial-size: 5 #初始化连接数量
      min-idle: 5 #最小空闲连接数
      max-active: 300 #最大并发连接数
      max-wait: 60000 #最大等待时间(60秒)
      time-between-eviction-runs-millis: 60000 #配置间隔多久进行一次检测,检测需要关闭的空闲连接,单位毫秒
      min-evictable-idle-time-millis: 300000 #一个连接在线程池中的生存时间,单位是毫秒
      validation-query: SELECT 1 FROM DUAL #验证查询
  jmx:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: hjc_tx_group
  security:
    user:
      name: hjc718
      password: Ble654321
server:
  compression:
    enabled: true #返回文档gzip
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048 #默认就是2048 byte
management:
  endpoints:
    metrics:
      sensitive: false
      enabled: true
    shutdown:
      enabled: true
    web:
      exposure:
        include: '*'
      base-path: /monitor
    health:
      sensitive: false
      enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
login:
  service:
    version: 1.0.0
    name: loginService
security:
  user:
    name: hjc718
    password: Ble654321
  basic:
    enabled: false
hjc:
  workerId: 0
  datacenterId: 0